### ISSUE TITLE
Cannot set custom directory for Rhythms

### ISSUE THREAD

**Issue by germede** [jjazzboss/JJazzLab#451] opened 2024-06-16 11:34 UTC
Hey there!
awesome software, but I've found some weird behavior:

I would like to change the directory for the rhythm files 
from the default /homes/<user>/JJazzLab/Rhythms 
to another (existing) /home/<user>/documents/jjazzlab/Rhythms

For that I'm opening Options menu > Rhythms and changing there the user directory for rhythm files. 
Everything goes and the programs ask to restart the program. 
However, regardless of choosing Yes or No, the text input doesn't change to my desired directory and it leaves in the default one.
Also there is no clue in the console for what's happening.
When starting the program again, the default user directory /homes/<user>/JJazzLab/Rhythms is being recreated.

**Comment by jjazzboss** [comment] 2024-06-16 14:36
You're right, and the problem is actually for all OS. Will be fixed in next release.

**Closed** 2024-08-19 15:15 UTC
Labels: bug
